"""changed made_at to created_at

Revision ID: 13fde4cdedf9
Revises: 3582818504a3
Create Date: 2025-05-24 15:20:14.660503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13fde4cdedf9'
down_revision: Union[str, None] = '3582818504a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle_votes', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('c_review', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('c_review', 'made_at')
    op.add_column('character', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('character', 'made_at')
    op.add_column('f_review', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('f_review', 'made_at')
    op.add_column('franchise', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.add_column('user', sa.Column('createed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('user', 'made_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('made_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('user', 'createed_at')
    op.drop_column('franchise', 'created_at')
    op.add_column('f_review', sa.Column('made_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('f_review', 'created_at')
    op.add_column('character', sa.Column('made_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('character', 'created_at')
    op.add_column('c_review', sa.Column('made_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_column('c_review', 'created_at')
    op.drop_column('battle_votes', 'created_at')
    # ### end Alembic commands ###
