"""Added Unique Constraint on Reviews

Revision ID: 3432f6dff460
Revises: 9451e3247e5a
Create Date: 2025-05-25 15:07:17.652762

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3432f6dff460'
down_revision: Union[str, None] = '9451e3247e5a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_char_review', 'c_review', ['user_id', 'char_id'])
    op.create_unique_constraint('uq_user_fran_review', 'f_review', ['user_id', 'franchise_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_fran_review', 'f_review', type_='unique')
    op.drop_constraint('uq_user_char_review', 'c_review', type_='unique')
    # ### end Alembic commands ###
