"""Made Franchise Name unique

Revision ID: 9451e3247e5a
Revises: bd30976cef0b
Create Date: 2025-05-24 16:55:04.600828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9451e3247e5a'
down_revision: Union[str, None] = 'bd30976cef0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('franchise_name_unique', 'franchise', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('franchise_name_unique', 'franchise', type_='unique')
    # ### end Alembic commands ###
