"""Removed some nullable=True

Revision ID: bd30976cef0b
Revises: 96a2ee024b2a
Create Date: 2025-05-24 16:37:27.077074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd30976cef0b'
down_revision: Union[str, None] = '96a2ee024b2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('franchise', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('franchise', 'description',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    op.alter_column('character', 'description',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    # ### end Alembic commands ###
